import { useEffect, useRef, useState } from "react";
import { useWorkspace, type EnrichedBlock } from "@/contexts/WorkspaceContext";
import { appendAuditEvent } from "@/lib/audit";
import { invokeProtectedFunction } from "@/lib/protectedInvoke";
import { toast } from "sonner";
import { jsPDF } from "jspdf";
import { StepGuide } from "./StepGuide";

interface HtmlExportMeta {
  filename: string;
  url: string;
}

const WEBSITE_TYPE_OPTIONS = [
  { value: "", label: "Select website type…" },
  { value: "existing", label: "Content for an existing website" },
  { value: "new", label: "Content for a new website" },
];

const SubmitPanel = () => {
  const ws = useWorkspace();
  const [agreed, setAgreed] = useState(false);
  const [websiteType, setWebsiteType] = useState("");
  const htmlExportRef = useRef<HtmlExportMeta | null>(null);

  useEffect(() => {
    return () => {
      if (htmlExportRef.current?.url) {
        URL.revokeObjectURL(htmlExportRef.current.url);
      }
    };
  }, []);

  const buildHtmlExport = (download: boolean): HtmlExportMeta => {
    if (htmlExportRef.current?.url) {
      URL.revokeObjectURL(htmlExportRef.current.url);
    }

    const title = ws.currentBrief?.projectTitle || "Company Name Project";
    const escapeHtml = (value: unknown) =>
      String(value ?? "")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;");

    // Render the actual enriched page (headline, sections, CTA) just like the
    // PDF report; fall back to the brief sections if enrichment never ran.
    const exportBlocks = ws.enrichedBlocks.length > 0
      ? ws.enrichedBlocks
      : (ws.currentBrief?.contentSections?.length
          ? ws.currentBrief.contentSections
          : (ws.currentBrief?.keyMessages || [])
        ).map((s, i) => ({ name: `Section ${i + 1}`, fields: [{ label: "Content", value: s, heading: false }] }));

    const bodyHtml = exportBlocks.map(block => {
      const inner = block.fields.map(field => {
        if (field.image && field.value) {
          // data URL from the builder upload - render the actual image
          return `<img class="uploaded" src="${field.value}" alt="${escapeHtml(field.label)}" />`;
        }
        const value = escapeHtml(field.value);
        if (!value) return "";
        if (field.heading) return `<h2>${value}</h2>`;
        if (/cta/i.test(field.label)) return `<p><a class="cta" href="#">${value}</a></p>`;
        return `<p>${value}</p>`;
      }).filter(Boolean).join("\n      ");
      return `<section>\n      ${inner}\n    </section>`;
    }).join("\n    ");

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <style>
    *{box-sizing:border-box} body{margin:0;font-family:Arial,sans-serif;background:#f8fafc;color:#0f172a}
    header{background:#003087;color:#fff;padding:24px 28px}
    h1{margin:0;font-size:30px;line-height:1.2}
    main{max-width:980px;margin:24px auto;background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:24px}
    section{padding:8px 0;border-bottom:1px solid #eef2f7} section:last-of-type{border-bottom:none}
    h2{font-size:20px;margin:8px 0;color:#003087}
    p{line-height:1.7;margin:0 0 14px}
    .cta{display:inline-block;background:#003087;color:#fff;text-decoration:none;padding:10px 18px;border-radius:8px;font-weight:bold}
    .uploaded{max-width:100%;height:auto;border-radius:8px;display:block;margin:10px 0}
    footer{margin-top:20px;color:#64748b;font-size:12px}
  </style>
</head>
<body>
  <header>
    <h1>${escapeHtml(title)}</h1>
  </header>
  <main>
    ${bodyHtml || "<p>No content available.</p>"}
    <footer>Layout: ${escapeHtml(ws.layout || "hero")} · Generated by Prompt Muse</footer>
  </main>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const safeTitle = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    const filename = `${safeTitle || "company-name-project"}.html`;

    if (download) {
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      toast.success("HTML export downloaded");
    }

    const meta = { filename, url };
    htmlExportRef.current = meta;
    return meta;
  };

  const wrapText = (pdf: jsPDF, text: string, x: number, y: number, maxWidth: number, lineHeight = 5): number => {
    const lines = pdf.splitTextToSize(String(text ?? ""), maxWidth) as string[];
    lines.forEach(line => { pdf.text(line, x, y); y += lineHeight; });
    return y;
  };

  const checkPageBreak = (doc: jsPDF, y: number, needed = 14): number => {
    if (y + needed > 280) { doc.addPage(); return 16; }
    return y;
  };

  const sectionHeader = (doc: jsPDF, label: string, y: number, left: number, right: number): number => {
    y = checkPageBreak(doc, y, 16);
    doc.setFillColor(0, 48, 135);
    doc.rect(left, y, right - left, 7, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text(label.toUpperCase(), left + 3, y + 5);
    doc.setTextColor(15, 30, 45);
    return y + 10;
  };

  const kvRow = (doc: jsPDF, label: string, value: string, y: number, left: number, maxWidth: number): number => {
    y = checkPageBreak(doc, y);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(80, 100, 130);
    doc.text(label, left, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(15, 30, 45);
    y = wrapText(doc, value, left + 42, y, maxWidth - 42, 4.5);
    return y + 1;
  };

  const downloadPieReportPdf = (submittedAt: Date, htmlMeta?: HtmlExportMeta | null) => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const left = 14;
    const right = 196;
    const maxWidth = right - left;
    let y = 16;

    const projectTitle = ws.currentBrief?.projectTitle || "Untitled Project";
    const submitter = `${ws.user?.firstName || ""} ${ws.user?.lastName || ""}`.trim() || "Unknown";
    const email = ws.user?.email || "Unknown";
    const phone = ws.user?.phone || "-";
    const empNumber = ws.user?.empNumber || "-";
    const department = ws.user?.department || "-";
    const homeRegion = ws.user?.country || "Unknown";
    const targetRegion = ws.pieResult?.jurisdiction?.country_detected || homeRegion;
    const wsTypLabel = WEBSITE_TYPE_OPTIONS.find(o => o.value === websiteType)?.label || "Not specified";
    const audience = ws.prelim.audience || "-";
    const score = ws.reviewData?.overallScore || 0;
    const sc = ws.reviewData?.scores || { compliance: 0, grammar: 0, brandVoice: 0, accessibility: 0 };
    const pieScore = ws.pieResult?.pie_score ?? "-";
    const pieGrade = ws.pieResult?.pie_grade ?? "-";
    const submittedAtLocal = submittedAt.toLocaleString();
    const submittedAtIso = submittedAt.toISOString();

    // ── Cover header ──
    doc.setFillColor(0, 48, 135);
    doc.rect(0, 0, 210, 28, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(255, 255, 255);
    doc.text("PIE Submission Report", left, 12);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`${projectTitle}  ·  Generated ${submittedAtLocal}`, left, 21);
    doc.setTextColor(15, 30, 45);
    y = 36;

    // ── 1. User Details ──
    y = sectionHeader(doc, "1. Submitter Details", y, left, right);
    y = kvRow(doc, "Name", submitter, y, left, maxWidth);
    y = kvRow(doc, "Email", email, y, left, maxWidth);
    y = kvRow(doc, "Phone", phone, y, left, maxWidth);
    y = kvRow(doc, "Employee No.", empNumber, y, left, maxWidth);
    y = kvRow(doc, "Department", department, y, left, maxWidth);
    y = kvRow(doc, "Home Region", homeRegion, y, left, maxWidth);
    y = kvRow(doc, "Target Region", targetRegion, y, left, maxWidth);
    y = kvRow(doc, "Submitted At", submittedAtLocal, y, left, maxWidth);
    y = kvRow(doc, "ISO Timestamp", submittedAtIso, y, left, maxWidth);
    y += 4;

    // ── 2. Project Details ──
    y = sectionHeader(doc, "2. Project Details", y, left, right);
    y = kvRow(doc, "Project Title", projectTitle, y, left, maxWidth);
    y = kvRow(doc, "Goal", ws.currentBrief?.goal || "-", y, left, maxWidth);
    y = kvRow(doc, "Audience", ws.currentBrief?.audience || audience, y, left, maxWidth);
    y = kvRow(doc, "Tone & Style", ws.currentBrief?.toneAndStyle || "-", y, left, maxWidth);
    y = kvRow(doc, "Website Type", wsTypLabel, y, left, maxWidth);
    y = kvRow(doc, "Layout", ws.layout || "hero", y, left, maxWidth);
    y += 4;

    // ── 3. PIE Scorecard ──
    y = sectionHeader(doc, "3. PIE Scorecard", y, left, right);
    y = kvRow(doc, "PIE Score", `${pieScore}/100  (Grade ${pieGrade})`, y, left, maxWidth);
    y = kvRow(doc, "PIE Interpretation", ws.pieResult?.pie_interpretation || "-", y, left, maxWidth);
    if (ws.pieResult?.breakdown) {
      const bd = ws.pieResult.breakdown;
      y = kvRow(doc, "  Compliance", `${bd.compliance}/100`, y, left, maxWidth);
      y = kvRow(doc, "  Tone", `${bd.tone}/100`, y, left, maxWidth);
      y = kvRow(doc, "  Audience", `${bd.audience}/100`, y, left, maxWidth);
      y = kvRow(doc, "  Readability", `${bd.readability}/100`, y, left, maxWidth);
    }
    y += 2;
    y = kvRow(doc, "Review Score", `${score}/100`, y, left, maxWidth);
    y = kvRow(doc, "  Compliance", `${sc.compliance}/100`, y, left, maxWidth);
    y = kvRow(doc, "  Grammar", `${sc.grammar}/100`, y, left, maxWidth);
    y = kvRow(doc, "  Brand Voice", `${sc.brandVoice}/100`, y, left, maxWidth);
    y = kvRow(doc, "  Accessibility", `${sc.accessibility}/100`, y, left, maxWidth);
    y += 4;

    // ── 4. Page Content Preview ──
    y = sectionHeader(doc, "4. Page Content Preview", y, left, right);
    const blocks: EnrichedBlock[] = ws.enrichedBlocks.length > 0
      ? ws.enrichedBlocks
      : (ws.currentBrief?.contentSections || []).map((s, i) => ({
          name: `Section ${i + 1}`,
          fields: [{ label: "Content", value: s }],
        }));

    if (blocks.length === 0) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(120, 120, 120);
      doc.text("No enriched content available.", left, y);
      doc.setTextColor(15, 30, 45);
      y += 6;
    } else {
      for (const block of blocks) {
        y = checkPageBreak(doc, y, 18);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(0, 94, 184);
        doc.text(`▸ ${block.name}`, left, y);
        doc.setTextColor(15, 30, 45);
        y += 5;
        for (const field of block.fields) {
          if (field.image && field.value) {
            // Embed uploaded images so the reviewer can see/approve them.
            try {
              const props = doc.getImageProperties(field.value);
              const dispW = Math.min(maxWidth - 3, 90);
              const dispH = props.width > 0 ? (props.height / props.width) * dispW : 40;
              y = checkPageBreak(doc, y, dispH + 8);
              doc.setFont("helvetica", "bold");
              doc.setFontSize(8);
              doc.setTextColor(100, 120, 150);
              doc.text((field.label || "IMAGE").toUpperCase(), left + 3, y);
              y += 4;
              doc.addImage(field.value, left + 3, y, dispW, dispH);
              y += dispH + 3;
              doc.setTextColor(15, 30, 45);
            } catch {
              y = checkPageBreak(doc, y, 10);
              doc.setFont("helvetica", "italic");
              doc.setFontSize(9);
              doc.setTextColor(120, 120, 120);
              y = wrapText(doc, `[Image: ${field.label}]`, left + 3, y, maxWidth - 3, 4.5);
              doc.setTextColor(15, 30, 45);
              y += 2;
            }
            continue;
          }
          y = checkPageBreak(doc, y, 10);
          doc.setFont("helvetica", "bold");
          doc.setFontSize(8);
          doc.setTextColor(100, 120, 150);
          doc.text(field.label.toUpperCase(), left + 3, y);
          y += 4;
          doc.setFont("helvetica", "normal");
          doc.setFontSize(9);
          doc.setTextColor(15, 30, 45);
          y = wrapText(doc, field.value || "-", left + 3, y, maxWidth - 3, 4.5);
          y += 2;
        }
        y += 3;
      }
    }

    // ── 5. Materials Uploaded ──
    y = sectionHeader(doc, "5. Materials Uploaded", y, left, right);
    if (ws.materials.length === 0) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(120, 120, 120);
      doc.text("No materials uploaded.", left, y);
      doc.setTextColor(15, 30, 45);
      y += 6;
    } else {
      for (const mat of ws.materials) {
        y = checkPageBreak(doc, y, 10);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(15, 30, 45);
        doc.text(`${mat.type.toUpperCase()}  ·  Stage: ${mat.stage}`, left + 2, y);
        y += 4.5;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        y = wrapText(doc, `Name: ${mat.name}`, left + 4, y, maxWidth - 4, 4.5);
        y = wrapText(doc, `Source: ${mat.source}`, left + 4, y, maxWidth - 4, 4.5);
        y += 2;
      }
    }
    y += 2;

    // ── 6. Review Questionnaire ──
    y = sectionHeader(doc, "6. Review Questionnaire - Issue Decisions", y, left, right);
    const allIssues = [
      ...(ws.reviewData?.complianceIssues || []).map(i => ({ ...i, category: "Compliance" })),
      ...(ws.reviewData?.grammarIssues || []).map(i => ({ ...i, category: "Grammar" })),
    ];

    if (allIssues.length === 0) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(120, 120, 120);
      doc.text("No review issues recorded.", left, y);
      doc.setTextColor(15, 30, 45);
      y += 6;
    } else {
      for (const issue of allIssues) {
        y = checkPageBreak(doc, y, 24);
        const decision = ws.reviewDecisions[issue.id];
        const decisionLabel = decision === "approved" ? "✓ ACCEPTED" : decision === "declined" ? "✕ DECLINED" : "- PENDING";
        const decisionR = decision === "approved" ? 22 : decision === "declined" ? 127 : 100;
        const decisionG = decision === "approved" ? 101 : decision === "declined" ? 29 : 100;
        const decisionB = decision === "approved" ? 52 : decision === "declined" ? 29 : 100;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(15, 30, 45);
        doc.text(`[${issue.category}]  ${issue.field}`, left + 2, y);
        doc.setTextColor(decisionR, decisionG, decisionB);
        doc.text(decisionLabel, right - 30, y);
        doc.setTextColor(15, 30, 45);
        y += 4.5;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        doc.setTextColor(80, 80, 80);
        y = wrapText(doc, `Severity: ${issue.severity.toUpperCase()}  ·  Issue: ${issue.issue}`, left + 4, y, maxWidth - 4, 4.5);
        if (issue.contentSnippet) {
          y = wrapText(doc, `Flagged text: "${issue.contentSnippet}"`, left + 4, y, maxWidth - 4, 4.5);
        }
        doc.setTextColor(22, 101, 52);
        y = wrapText(doc, `Recommendation: ${issue.recommendation}`, left + 4, y, maxWidth - 4, 4.5);
        doc.setTextColor(15, 30, 45);
        y += 3;
      }
    }

    // ── Footer on every page ──
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Company Name · PIE Report · ${projectTitle} · Page ${i} of ${pageCount}`,
        left, 291
      );
    }

    const safeTitle = projectTitle.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    doc.save(`${safeTitle || "project"}-pie-report.pdf`);
  };

  const handleExportHtml = () => {
    buildHtmlExport(true);
  };

  const handleDownloadPieReport = () => {
    const now = new Date();
    const htmlMeta = htmlExportRef.current || buildHtmlExport(false);
    downloadPieReportPdf(now, htmlMeta);
    toast.success("PIE Report downloaded");
  };

  const handleSubmit = async () => {
    if (!agreed) return;
    const submittedAt = new Date();
    // Download both deliverables synchronously within the click gesture so the
    // browser doesn't block the second download after the async notify call.
    const htmlMeta = buildHtmlExport(true);
    downloadPieReportPdf(submittedAt, htmlMeta);

    const payload = {
      projectTitle: ws.currentBrief?.projectTitle || "Untitled Project",
      submitter: `${ws.user?.firstName || ""} ${ws.user?.lastName || ""}`.trim(),
      submitterEmail: ws.user?.email || "",
      country: ws.user?.country || "",
      buildType: ws.prelim.buildType || "",
      websiteType: WEBSITE_TYPE_OPTIONS.find(o => o.value === websiteType)?.label || websiteType || "Not specified",
      score: ws.reviewData?.overallScore || 0,
    };

    try {
        const { data, error } = await invokeProtectedFunction<typeof payload, { simulated?: boolean; message?: string }>("notify-reviewer", payload);
      if (error) throw new Error(error.message);
      appendAuditEvent({
        eventType: "notification",
        actor: ws.user?.email || "unknown-user",
        details: {
          reviewer_notified: true,
          simulated: Boolean(data?.simulated),
          message: data?.message || null,
        },
      });
      if (data?.simulated) {
        toast.message("Reviewer notification simulated (configure env vars for live email)");
      } else {
        toast.success("Reviewer notification sent");
      }
    } catch (err: any) {
      appendAuditEvent({
        eventType: "notification",
        actor: ws.user?.email || "unknown-user",
        details: {
          reviewer_notified: false,
          error: err?.message || "Notification call failed",
        },
      });
    }

    ws.setSubmitted();
    appendAuditEvent({
      eventType: "submission",
      actor: ws.user?.email || "unknown-user",
      details: {
        projectTitle: ws.currentBrief?.projectTitle || "Untitled Project",
        score: ws.reviewData?.overallScore || 0,
        buildType: ws.prelim.buildType || "",
        websiteType: WEBSITE_TYPE_OPTIONS.find(o => o.value === websiteType)?.label || "Not specified",
        audience: ws.prelim.audience || "",
        submittedAt: submittedAt.toISOString(),
        htmlFile: htmlMeta.filename,
      },
    });
    toast.success("Project submitted for review!");
  };

  return (
    <div className="flex-1 overflow-y-auto p-7 animate-fade-up">
      <div className="max-w-[560px] mx-auto">
      <StepGuide
        step={5}
        role="Submitter - final sign-off before human review"
        instruction="You are about to submit this project for final review by the IT and compliance team. This is the last step before the content can be published."
        actions={[
          "Select the website type - new build or content update for an existing site",
          "Download the PIE Report (PDF) - this is your audit record containing scores, all review decisions, and full content",
          "Export HTML - the working prototype of the page, ready for developer handoff",
          "Read and tick the compliance declaration - you are confirming the content has been reviewed",
          "Click Submit for Review - a notification is sent to the reviewer and the audit log is finalised",
        ]}
        nextStep="After submission, the IT review team will perform a final assessment. You will be contacted if changes are required before publication."
        variant="checkpoint"
      />
      <div className="bg-card border-[1.5px] border-border rounded-[20px] shadow-pf-md p-9 w-full">
        <h2 className="font-serif text-xl text-pf-dark mb-1">Export and Submit</h2>
        <p className="text-[13px] text-muted-foreground mb-5">
          Export the generated page as HTML, then submit for final review.
        </p>

        <div className="grid grid-cols-2 gap-2 mb-4">
          <div className="bg-secondary border border-border rounded-md p-2.5 col-span-2">
            <div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground/60 mb-1">Website Type</div>
            <select
              value={websiteType}
              onChange={e => setWebsiteType(e.target.value)}
              className="w-full bg-card border border-border rounded-md px-2.5 py-1.5 text-[13px] font-semibold text-foreground outline-none focus:border-primary transition-colors"
            >
              {WEBSITE_TYPE_OPTIONS.map(opt => (
                <option key={opt.value} value={opt.value}>{opt.label}</option>
              ))}
            </select>
          </div>
          <MetaBox label="Audience" value={ws.prelim.audience || "-"} />
          <MetaBox label="Region" value={ws.user?.country || "-"} />
          <MetaBox label="Score" value={ws.reviewData ? `${ws.reviewData.overallScore}/100` : "-"} />
        </div>

        <div className="bg-secondary border border-border rounded-md p-3 text-[12.5px] text-muted-foreground leading-relaxed max-h-[120px] overflow-y-auto mb-3">
          By submitting this project, I confirm that all content has been reviewed for brand compliance,
          accessibility standards (WCAG 2.1 AA), and regulatory requirements applicable to the target
          jurisdiction. I understand that the IT review team will perform a final assessment before
          publication. Any content flagged during the automated review has been addressed or acknowledged.
          This submission is subject to Company Name internal content governance policy.
        </div>

        <label className="flex items-center gap-2.5 mb-5 cursor-pointer">
          <input
            type="checkbox"
            checked={agreed}
            onChange={e => setAgreed(e.target.checked)}
            className="w-[15px] h-[15px] accent-primary cursor-pointer"
          />
          <span className="text-[13px] font-medium text-foreground">I agree to the terms and conditions</span>
        </label>

        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={handleDownloadPieReport}
            className="w-full bg-card border border-border text-foreground rounded-md py-3 text-sm font-bold hover:border-primary hover:text-primary transition-all"
          >
            Download PIE Report
          </button>
          <button
            onClick={handleExportHtml}
            className="w-full bg-card border border-border text-foreground rounded-md py-3 text-sm font-bold hover:border-primary hover:text-primary transition-all"
          >
            Export HTML
          </button>
          <button
            onClick={handleSubmit}
            disabled={!agreed}
            className="w-full bg-btn-gradient text-primary-foreground rounded-md py-3 text-sm font-bold shadow-pf hover:shadow-pf-md transition-all disabled:opacity-40 disabled:cursor-not-allowed col-span-2"
          >
            Submit for Review
          </button>
        </div>
      </div>
      </div>
    </div>
  );
};

function MetaBox({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-secondary border border-border rounded-md p-2.5">
      <div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground/60 mb-0.5">{label}</div>
      <div className="text-[13px] font-semibold text-foreground">{value}</div>
    </div>
  );
}

export default SubmitPanel;
